/* Taxonomy source of truth for this prototype.
   Generated by build-taxonomy.mjs from the JSON files one level up — do not
   hand-edit; change the JSON and regenerate.

     functionalDomains  <- new_functional_domains.json   (19 domains, 4 net-new)
     expertiseByDomain  <- new_expertises.json           (243 expertises)
     industryGroups     <- new_industries.json           (40 industries, 13 groups, 17 net-new)
     existingIndustries <- exisiting_industries.json     (23, all of which survive)
     agendas            <- agends.json                   (13, flat, no parentage)
     expertiseAliases   <- expertise_amendments.json     (39 retired -> final pairs)

   `isNew` marks the values the taxonomy change adds, so the filter panel can
   show what is actually new rather than only what the final list contains.

   Plain global, not an ES module: this page is opened straight off the file
   system, where module scripts are blocked by CORS. */

window.MU_TAXONOMY = (function () {
  const functionalDomains = [
  {
    "name": "Accounting & Finance",
    "isNew": false
  },
  {
    "name": "Blockchain, Crypto & FinTech",
    "isNew": false
  },
  {
    "name": "Chief of Staff & Founder's Office",
    "isNew": false
  },
  {
    "name": "Communication & Leadership",
    "isNew": false
  },
  {
    "name": "Consulting & Strategy",
    "isNew": false
  },
  {
    "name": "Content Creation",
    "isNew": false
  },
  {
    "name": "Data Science & AI",
    "isNew": false
  },
  {
    "name": "Entrepreneurship & Startups",
    "isNew": false
  },
  {
    "name": "Legal, Policies & Economics",
    "isNew": false
  },
  {
    "name": "Human Resources & Org Strategy",
    "isNew": false
  },
  {
    "name": "Operations & Supply Chain",
    "isNew": false
  },
  {
    "name": "PEVC, Banking & Investments",
    "isNew": false
  },
  {
    "name": "Sales, Brand & Marketing",
    "isNew": false
  },
  {
    "name": "Sustainability & ESG",
    "isNew": false
  },
  {
    "name": "Tech & Product",
    "isNew": false
  },
  {
    "name": "Coaching & Mental Wellbeing",
    "isNew": true
  },
  {
    "name": "Cybersecurity, Privacy & Risk",
    "isNew": true
  },
  {
    "name": "Media, PR & Creator Economy",
    "isNew": true
  },
  {
    "name": "Sports, Gaming & Performance",
    "isNew": true
  }
];

  const expertiseByDomain = {
  "Accounting & Finance": [
    "Corporate Finance",
    "Financial Accounting & Reporting",
    "Financial Planning & Analysis (FP&A)",
    "Financial Modelling & Valuation",
    "Auditing & Assurance",
    "Taxation & Compliance",
    "Treasury & Cash Management",
    "Financial Risk Management",
    "Cost Accounting",
    "Project Finance",
    "Investor Relations",
    "Financial Systems & ERP"
  ],
  "Blockchain, Crypto & FinTech": [
    "Blockchain",
    "DeFi & Cryptocurrency",
    "Digital Payments & Wallets",
    "FinTech",
    "Tokenization & Digital Assets",
    "KYC & AML Compliance",
    "Data & Cyber Security",
    "Web3 & Metaverse",
    "Digital Finance",
    "Smart Contracts",
    "Stablecoins & CBDCs",
    "Open Banking & Embedded Finance",
    "Crypto Custody & Wallets"
  ],
  "Chief of Staff & Founder's Office": [
    "Internal Communication",
    "Stakeholder Management",
    "Executive Decision Support",
    "Business Research",
    "Strategic Planning & OKRs",
    "People & Culture",
    "Partnerships & Alliances",
    "Change Enablement",
    "Founder Office Operations",
    "Board & Investor Updates",
    "Special Projects",
    "Cross-Functional Execution"
  ],
  "Communication & Leadership": [
    "External Communication",
    "Public Speaking",
    "Negotiation & Influence",
    "Team Leadership",
    "Conflict Resolution",
    "Cross-Cultural Communication",
    "Crisis Communication",
    "Storytelling",
    "Personal Branding",
    "Leadership Presence",
    "Business Writing",
    "Facilitation",
    "Feedback & Coaching"
  ],
  "Consulting & Strategy": [
    "Corporate Strategy",
    "Growth & Market Entry Strategy",
    "Operational Excellence",
    "Business Transformation",
    "Competitive Intelligence",
    "Business Model Innovation",
    "Post-Merger Integration (PMI)",
    "Cost Transformation & Efficiency",
    "Management Consulting",
    "Market Research",
    "Scenario Planning",
    "Operating Model Design",
    "Commercial Due Diligence"
  ],
  "Content Creation": [
    "Social Media Strategy",
    "Audience Building",
    "Visual Storytelling",
    "Long-form Content",
    "SEO & Discoverability",
    "Content Monetisation",
    "AI Content Creation",
    "Content Analytics & Optimisation",
    "Short-Form Video",
    "Podcast Strategy",
    "Newsletter Building",
    "UGC Strategy"
  ],
  "Data Science & AI": [
    "Data Analytics & Visualization",
    "Data Engineering",
    "Machine Learning",
    "Natural Language Processing",
    "Generative AI",
    "Predictive Modelling",
    "Data Governance & Ethics",
    "Chatbots & Web Analytics",
    "AI Tools",
    "AI Agents & Agentic Systems",
    "MLOps",
    "Computer Vision",
    "Retrieval-Augmented Generation (RAG)"
  ],
  "Entrepreneurship & Startups": [
    "Product Market Fit",
    "Fundraising & Investor Pitching",
    "Go-to-Market Strategy (GTM)",
    "Growth & Product-Led Growth",
    "Startup Ops & Scaling",
    "Zero-to-One Execution",
    "Founder Mindset & Resilience",
    "Minimum Viable Product",
    "Startup Valuation",
    "Bootstrapping",
    "Founder-Led Sales",
    "Cap Table Management",
    "Family Business & Succession"
  ],
  "Legal, Policies & Economics": [
    "Criminal & Civil Law",
    "Corporate & Commercial Law",
    "Regulatory Compliance",
    "Contract Drafting",
    "Public Policy & Advocacy",
    "IP Rights & Strategy",
    "Corporate Governance",
    "General Legal Advisory",
    "Employment Law",
    "Data Privacy Law",
    "Competition & Antitrust",
    "Dispute Resolution & Arbitration",
    "Economic Policy"
  ],
  "Human Resources & Org Strategy": [
    "Talent Acquisition & Employer Brand",
    "Performance Management",
    "Learning & Development",
    "Total Rewards & Compensation",
    "Organisational Design",
    "People Analytics",
    "Diversity, Equity & Inclusion",
    "Workplace Wellbeing",
    "People Strategy",
    "Workforce Planning",
    "Change Leadership",
    "Culture Transformation",
    "Employee Experience"
  ],
  "Operations & Supply Chain": [
    "Supply Chain Management",
    "Operations Research & Analysis",
    "Procurement & Sourcing",
    "Logistics & Distribution",
    "Lean & Six Sigma",
    "Inventory & Fulfilment",
    "S&OP & Demand Planning",
    "Retail Management",
    "Supplier Risk Management",
    "Quality Management",
    "Manufacturing Operations",
    "Cold Chain Operations",
    "Global Trade & Customs"
  ],
  "PEVC, Banking & Investments": [
    "Investment Banking & M&A",
    "Private Equity & Deal Structuring",
    "Venture Capital",
    "Capital Markets",
    "Equity Research",
    "Portfolio Management",
    "Term Sheets & Deal Negotiation",
    "Financial Due Diligence",
    "Corporate & Retail Banking",
    "Forex Markets",
    "Private Credit",
    "Derivatives Trading",
    "Fixed Income & Rates"
  ],
  "Sales, Brand & Marketing": [
    "Product & Brand Marketing",
    "Digital & Performance Marketing",
    "Business Development",
    "Marketing Analytics & RevOps",
    "Customer Experience",
    "Pricing & Revenue Strategy",
    "CRM & Sales Operations",
    "E-commerce & Social Commerce",
    "Consumer Behaviour & Psychology",
    "Account-Based Marketing",
    "Enterprise Sales",
    "Marketing Automation",
    "Customer Retention & Loyalty"
  ],
  "Sustainability & ESG": [
    "Sustainability Strategy",
    "ESG Reporting & Standards",
    "Sustainable & Impact Finance",
    "Carbon & ClimateTech",
    "Circular Economy",
    "Social Entrepreneurship",
    "Sustainable Product Design",
    "Climate Risk & Adaptation",
    "Decarbonisation & Net-Zero",
    "Sustainable Supply Chains",
    "Biodiversity & Nature",
    "GHG Accounting",
    "Water Stewardship"
  ],
  "Tech & Product": [
    "Product Management & Strategy",
    "Product Discovery & User Research",
    "Product Analytics",
    "Software Engineering",
    "DevOps & Cloud",
    "Platform Engineering",
    "Solutions Architecture",
    "Digital Transformation & IT Consulting",
    "UX/UI & Design Thinking",
    "Agile & Scrum",
    "Technical Program Management",
    "QA & Testing",
    "Mobile, IoT & Hardware"
  ],
  "Coaching & Mental Wellbeing": [
    "Counselling",
    "Career Coaching",
    "Life Coaching",
    "Executive Coaching",
    "Team Coaching",
    "Stress & Burnout Management",
    "Mindfulness & Meditation",
    "Resilience Coaching",
    "Positive Psychology",
    "Emotional Wellbeing",
    "Mental Health First Aid",
    "Coaching Ethics & Boundaries"
  ],
  "Cybersecurity, Privacy & Risk": [
    "Security Operations",
    "Cloud Security",
    "Application Security",
    "Identity & Access Management",
    "Threat Intelligence",
    "Incident Response",
    "Cyber Risk & Governance",
    "Data Privacy & Protection",
    "Privacy Engineering",
    "Business Continuity & Disaster Recovery",
    "DevSecOps",
    "Penetration Testing & Ethical Hacking",
    "Security Architecture"
  ],
  "Media, PR & Creator Economy": [
    "Media Relations",
    "Reputation Management",
    "Executive Communications",
    "Public Affairs Communications",
    "Influencer Partnerships",
    "Creator Revenue Models",
    "Creator Talent Management",
    "Brand Deal Negotiation",
    "UGC Strategy",
    "Creator Rights & Licensing",
    "Community Management",
    "Entertainment Marketing",
    "Communications Measurement"
  ],
  "Sports, Gaming & Performance": [
    "Sports Business Strategy",
    "League & Club Operations",
    "Sports Sponsorships",
    "Athlete Management",
    "Sports Analytics",
    "Sports Events & Venues",
    "Sports Media Rights",
    "Fan Engagement",
    "Esports Management",
    "Game Publishing",
    "Live Game Operations",
    "Game Monetisation",
    "Performance Coaching"
  ]
};

  const industryGroups = [
  {
    "group": "Technology, Digital & Electronics",
    "industries": [
      {
        "name": "Tech, IT, Telecom, AI and ML",
        "isNew": false
      },
      {
        "name": "Cybersecurity Products & Services",
        "isNew": true
      },
      {
        "name": "Data Centres & Cloud Infrastructure",
        "isNew": true
      },
      {
        "name": "Electronics and Consumer Goods",
        "isNew": false
      }
    ]
  },
  {
    "group": "Financial & Professional Services",
    "industries": [
      {
        "name": "Banking, Insurance, and Financial Services",
        "isNew": false
      },
      {
        "name": "Consulting, Legal, and Professional Services",
        "isNew": false
      },
      {
        "name": "Public Relations & Communications Services",
        "isNew": true
      }
    ]
  },
  {
    "group": "Consumer, Retail & Lifestyle",
    "industries": [
      {
        "name": "FMCG",
        "isNew": false
      },
      {
        "name": "Retail, E-commerce and Q-commerce",
        "isNew": false
      },
      {
        "name": "Consumer & Local Services",
        "isNew": true
      },
      {
        "name": "Beauty, Personal Care & Cosmetics",
        "isNew": true
      },
      {
        "name": "Luxury & Premium Brands",
        "isNew": true
      },
      {
        "name": "Pet Care & Animal Health",
        "isNew": true
      }
    ]
  },
  {
    "group": "Healthcare, Care & Wellness",
    "industries": [
      {
        "name": "Healthcare, Pharma and Medical Devices",
        "isNew": false
      },
      {
        "name": "Mental Health & Wellbeing Services",
        "isNew": true
      },
      {
        "name": "Childcare, Elder Care & Senior Living",
        "isNew": true
      }
    ]
  },
  {
    "group": "Industrial Manufacturing & Materials",
    "industries": [
      {
        "name": "Chemicals and Petrochemicals",
        "isNew": false
      },
      {
        "name": "Automotive and EV",
        "isNew": false
      },
      {
        "name": "Steel and Metals",
        "isNew": false
      },
      {
        "name": "Textiles and Fashion",
        "isNew": false
      },
      {
        "name": "Mining and Minerals",
        "isNew": false
      }
    ]
  },
  {
    "group": "Energy, Environment & Utilities",
    "industries": [
      {
        "name": "Oil, Gas, Solar and Energy",
        "isNew": false
      },
      {
        "name": "Environment, Utilities and GreenTech",
        "isNew": false
      }
    ]
  },
  {
    "group": "Aerospace, Defense & Maritime",
    "industries": [
      {
        "name": "Aerospace, Defense and SpaceTech",
        "isNew": false
      },
      {
        "name": "Maritime, Ports & Shipping",
        "isNew": true
      }
    ]
  },
  {
    "group": "Transport, Logistics & Supply Chain",
    "industries": [
      {
        "name": "Aviation & Airlines",
        "isNew": true
      },
      {
        "name": "Logistics and Supply Chain",
        "isNew": false
      }
    ]
  },
  {
    "group": "Construction, Real Estate & Security",
    "industries": [
      {
        "name": "Construction and Real Estate",
        "isNew": false
      },
      {
        "name": "Facility Management & Private Security",
        "isNew": true
      }
    ]
  },
  {
    "group": "Agriculture, Food & Bioeconomy",
    "industries": [
      {
        "name": "Agriculture, AgriTech and FoodTech",
        "isNew": false
      }
    ]
  },
  {
    "group": "Media, Culture, Gaming & Experiences",
    "industries": [
      {
        "name": "Media and Entertainment",
        "isNew": false
      },
      {
        "name": "Creator Economy & Influencer Marketing",
        "isNew": true
      },
      {
        "name": "Gaming & Esports",
        "isNew": true
      },
      {
        "name": "Sports, Fitness & Recreation",
        "isNew": true
      },
      {
        "name": "Art, Culture & Museums",
        "isNew": true
      },
      {
        "name": "Events, Exhibitions & Experience Management",
        "isNew": true
      }
    ]
  },
  {
    "group": "Travel, Tourism & Hospitality",
    "industries": [
      {
        "name": "Hospitality and Tourism",
        "isNew": false
      }
    ]
  },
  {
    "group": "Public, Education & Social Impact",
    "industries": [
      {
        "name": "Government and Public Sector",
        "isNew": false
      },
      {
        "name": "Education and EdTech",
        "isNew": false
      },
      {
        "name": "Non-Profit and Social Impact",
        "isNew": false
      }
    ]
  }
];

  const existingIndustries = [
  "Aerospace, Defense and SpaceTech",
  "Agriculture, AgriTech and FoodTech",
  "Automotive and EV",
  "Banking, Insurance, and Financial Services",
  "Chemicals and Petrochemicals",
  "Construction and Real Estate",
  "Consulting, Legal, and Professional Services",
  "Education and EdTech",
  "Electronics and Consumer Goods",
  "Environment, Utilities and GreenTech",
  "FMCG",
  "Government and Public Sector",
  "Healthcare, Pharma and Medical Devices",
  "Hospitality and Tourism",
  "Logistics and Supply Chain",
  "Media and Entertainment",
  "Mining and Minerals",
  "Non-Profit and Social Impact",
  "Oil, Gas, Solar and Energy",
  "Retail, E-commerce and Q-commerce",
  "Steel and Metals",
  "Tech, IT, Telecom, AI and ML",
  "Textiles and Fashion"
];

  const agendas = [
  "Resume Review",
  "Interview Prep",
  "Case Guestimates",
  "Portfolio & Assignment Review",
  "Career Discovery",
  "Industry Trends & Insights",
  "Pitchdeck Review",
  "Startup Fundraising",
  "Develop Networking Skills",
  "Communication Skills",
  "Assignment Review",
  "Last Mile Prep (LMP)",
  "Domain Practicums"
];

  const expertiseAliases = [
  {
    "from": "Web 3.0 & Metaverse",
    "to": "Web3 & Metaverse",
    "domain": "Blockchain, Crypto & FinTech",
    "action": "RENAME"
  },
  {
    "from": "Digital Financial Sciences",
    "to": "Digital Finance",
    "domain": "Blockchain, Crypto & FinTech",
    "action": "RENAME"
  },
  {
    "from": "OKR Formulation",
    "to": "Strategic Planning & OKRs",
    "domain": "Chief of Staff & Founder's Office",
    "action": "RENAME"
  },
  {
    "from": "People Culture & Growth",
    "to": "People & Culture",
    "domain": "Chief of Staff & Founder's Office",
    "action": "RENAME"
  },
  {
    "from": "Cross-Cultural Diversity",
    "to": "Cross-Cultural Communication",
    "domain": "Communication & Leadership",
    "action": "RENAME"
  },
  {
    "from": "Social Media Brand Strategy",
    "to": "Social Media Strategy",
    "domain": "Content Creation",
    "action": "RENAME"
  },
  {
    "from": "Long-form Content Building",
    "to": "Long-form Content",
    "domain": "Content Creation",
    "action": "RENAME"
  },
  {
    "from": "SEO & Discoverability Strategy",
    "to": "SEO & Discoverability",
    "domain": "Content Creation",
    "action": "RENAME"
  },
  {
    "from": "AI Content Generation",
    "to": "AI Content Creation",
    "domain": "Content Creation",
    "action": "RENAME"
  },
  {
    "from": "Data Analytics",
    "to": "Data Analytics & Visualization",
    "domain": "Data Science & AI",
    "action": "MERGE"
  },
  {
    "from": "Data Visualization",
    "to": "Data Analytics & Visualization",
    "domain": "Data Science & AI",
    "action": "MERGE"
  },
  {
    "from": "Startup Fundraising",
    "to": "Fundraising & Investor Pitching",
    "domain": "Entrepreneurship & Startups",
    "action": "MERGE"
  },
  {
    "from": "Growth Hacking",
    "to": "Growth & Product-Led Growth",
    "domain": "Entrepreneurship & Startups",
    "action": "RENAME"
  },
  {
    "from": "Investor Pitchbook",
    "to": "Fundraising & Investor Pitching",
    "domain": "Entrepreneurship & Startups",
    "action": "MERGE"
  },
  {
    "from": "Talent Acquisition & Recruitment",
    "to": "Talent Acquisition & Employer Brand",
    "domain": "Human Resources & Org Strategy",
    "action": "MERGE"
  },
  {
    "from": "Compensation & Benefits",
    "to": "Total Rewards & Compensation",
    "domain": "Human Resources & Org Strategy",
    "action": "RENAME"
  },
  {
    "from": "HR Analytics",
    "to": "People Analytics",
    "domain": "Human Resources & Org Strategy",
    "action": "RENAME"
  },
  {
    "from": "Employer Branding",
    "to": "Talent Acquisition & Employer Brand",
    "domain": "Human Resources & Org Strategy",
    "action": "MERGE"
  },
  {
    "from": "Inventory Optimisation",
    "to": "Inventory & Fulfilment",
    "domain": "Operations & Supply Chain",
    "action": "MERGE"
  },
  {
    "from": "Demand Forecasting & Planning",
    "to": "S&OP & Demand Planning",
    "domain": "Operations & Supply Chain",
    "action": "RENAME"
  },
  {
    "from": "Warehouse & Fulfilment",
    "to": "Inventory & Fulfilment",
    "domain": "Operations & Supply Chain",
    "action": "MERGE"
  },
  {
    "from": "Investment Banking",
    "to": "Investment Banking & M&A",
    "domain": "PEVC, Banking & Investments",
    "action": "MERGE"
  },
  {
    "from": "Private Equity",
    "to": "Private Equity & Deal Structuring",
    "domain": "PEVC, Banking & Investments",
    "action": "MERGE"
  },
  {
    "from": "Equity Research & Analysis",
    "to": "Equity Research",
    "domain": "PEVC, Banking & Investments",
    "action": "RENAME"
  },
  {
    "from": "M&A Deal Advisory",
    "to": "Investment Banking & M&A",
    "domain": "PEVC, Banking & Investments",
    "action": "MERGE"
  },
  {
    "from": "Term Sheet & Deal Negotiation",
    "to": "Private Equity & Deal Structuring",
    "domain": "PEVC, Banking & Investments",
    "action": "MERGE"
  },
  {
    "from": "Financial Markets",
    "to": "Capital Markets",
    "domain": "PEVC, Banking & Investments",
    "action": "MERGE"
  },
  {
    "from": "Product Marketing",
    "to": "Product & Brand Marketing",
    "domain": "Sales, Brand & Marketing",
    "action": "MERGE"
  },
  {
    "from": "Brand Strategy",
    "to": "Product & Brand Marketing",
    "domain": "Sales, Brand & Marketing",
    "action": "MERGE"
  },
  {
    "from": "Dropshipping & E-commerce",
    "to": "E-commerce & Social Commerce",
    "domain": "Sales, Brand & Marketing",
    "action": "RENAME"
  },
  {
    "from": "Consumer Behavior & Psychology",
    "to": "Consumer Behaviour & Psychology",
    "domain": "Sales, Brand & Marketing",
    "action": "RENAME"
  },
  {
    "from": "Impact Investing",
    "to": "Sustainable & Impact Finance",
    "domain": "Sustainability & ESG",
    "action": "MERGE"
  },
  {
    "from": "Green Finance",
    "to": "Sustainable & Impact Finance",
    "domain": "Sustainability & ESG",
    "action": "MERGE"
  },
  {
    "from": "Product Management",
    "to": "Product Management & Strategy",
    "domain": "Tech & Product",
    "action": "RENAME"
  },
  {
    "from": "Digital Transformation",
    "to": "Digital Transformation & IT Consulting",
    "domain": "Tech & Product",
    "action": "MERGE"
  },
  {
    "from": "UI/UX Design",
    "to": "UX/UI & Design Thinking",
    "domain": "Tech & Product",
    "action": "MERGE"
  },
  {
    "from": "Mobile & IoT",
    "to": "Mobile, IoT & Hardware",
    "domain": "Tech & Product",
    "action": "RENAME"
  },
  {
    "from": "Design Thinking",
    "to": "UX/UI & Design Thinking",
    "domain": "Tech & Product",
    "action": "MERGE"
  },
  {
    "from": "IT Consulting",
    "to": "Digital Transformation & IT Consulting",
    "domain": "Tech & Product",
    "action": "MERGE"
  }
];

  const allExpertise = Object.values(expertiseByDomain).flat();
  const allIndustries = industryGroups.flatMap((g) => g.industries.map((i) => i.name));

  return {
    functionalDomains, expertiseByDomain, industryGroups, existingIndustries,
    agendas, expertiseAliases, allExpertise, allIndustries,
  };
})();
